export const HTML_TAGS = {
	p: "p",
	span: "span",
	div: "div",
	h1: "h1",
	h2: "h2",
	h3: "h3",
	h4: "h4",
	h5: "h5",
	h6: "h6",
};

export const SIZE = {
  small: "small",
  medium: "medium",
  large: "large",
};

export const LABEL = {
	back: "back",
	favourite: "favourite",
	max: "MAX:",
	min: "MIN:",
	province: "Provincia",
	temperature: "Temperatura:",
	temperatureMax: "Temp. Máxima:",
	temperatureMin: "Temp. Mínima:",
	humidity: "Humedad:",
	uv: "Índice max. uv:",
	wind: "Viento:",
	loading: "Cargando...",
	error: "Hubo un error al cargar los datos",
	noResults: "No hay resultados",
	seletProvince: "Selecciona una provincia 🌍",
	favListButton: "Lista de favoritos",
	nextDays: "Próximos días",
  seeMore: "Ver más",
};

export const UNITS = {
  celsius: "°C",
  percent: "%",
  kmh: "km/h",
};

export const VARIANT = {
	primary: "primary",
	secondary: "secondary",
	success: "success",
	danger: "danger",
	warning: "warning",
	info: "info",
	standard: "standard",
  outlined: "outlined",
};

export const PROVINCE_ID = {
	Almería: 1,
	Albacete: 3,
	Alicante: 4,
	Ávila: 5,
	Badajoz: 6,
	Baleares: 7,
	Barcelona: 8,
	Burgos: 9,
	Cáceres: 10,
	Cádiz: 11,
	Castellón: 12,
	Ciudad_Real: 13,
	Córdoba: 14,
	A_Coruña: 15,
	Cuenca: 16,
	Girona: 17,
	Granada: 18,
	Guadalajara: 19,
	Gipuzkoa: 20,
	Huelva: 21,
	Huesca: 22,
	Jaén: 23,
	León: 24,
	Lleida: 25,
	La_Rioja: 26,
	Lugo: 27,
	Madrid: 28,
	Málaga: 29,
	Murcia: 30,
	Navarra: 31,
	Ourense: 32,
	Asturias: 33,
	Palencia: 34,
	Las_Palmas: 35,
	Pontevedra: 36,
	Salamanca: 37,
	Santa_Cruz_de_Tenerife: 38,
	Cantabria: 39,
	Segovia: 40,
	Sevilla: 41,
	Soria: 42,
	Tarragona: 43,
	Teruel: 44,
	Toledo: 45,
	Valencia: 46,
	Valladolid: 47,
	Vizcaya: 48,
	Zamora: 49,
	Zaragoza: 50,
	Ceuta: 51,
	Melilla: 52,
};

