export const HTML_TAGS = {
	p: "p",
	span: "span",
	div: "div",
	h1: "h1",
	h2: "h2",
	h3: "h3",
	h4: "h4",
	h5: "h5",
	h6: "h6",
};

export const SIZE = {
  small: "small",
  medium: "medium",
  large: "large",
};

export const LABEL = {
	back: "back",
	favourite: "favourite",
	max: "MAX:",
	min: "MIN:",
	province: "Provincia",
	temperature: "Temperatura:",
	temperatureMax: "Temp. Máxima:",
	temperatureMin: "Temp. Mínima:",
	humidity: "Humedad:",
	uv: "Índice max. uv:",
	wind: "Viento:",
};

export const UNITS = {
  celsius: "°C",
  percent: "%",
  kmh: "km/h",
};

export const VARIANT = {
	primary: "primary",
	secondary: "secondary",
	success: "success",
	danger: "danger",
	warning: "warning",
	info: "info",
	standard: "standard",
  outlined: "outlined",
};

export const PRIVINCE = {
  15: "A Coruña",
  3: "Albacete",
  4: "Alicante",
  1: "Almería",
  33: "Asturias",
  5: "Ávila",
  6: "Badajoz",
  7: "Baleares",
  8: "Barcelona",
  9: "Burgos",
  10: "Cáceres",
  11: "Cádiz",
  39: "Cantabria",
  12: "Castellón",
  51: "Ceuta",
  13: "Ciudad Real",
  14: "Córdoba",
  16: "Cuenca",
  20: "Gipuzkoa",
  17: "Girona",
  18: "Granada",
  19: "Guadalajara",
  21: "Huelva",
  22: "Huesca",
  23: "Jaén",
  26: "La Rioja",
  35: "Las Palmas",
  24: "León",
  25: "Lleida",
  27: "Lugo",
  28: "Madrid",
  29: "Málaga",
  52: "Melilla",
  30: "Murcia",
  31: "Navarra",
  32: "Ourense",
  34: "Palencia",
  36: "Pontevedra",
  37: "Salamanca",
  38: "Santa Cruz de Tenerife",
  40: "Segovia",
  41: "Sevilla",
  42: "Soria",
  43: "Tarragona",
  44: "Teruel",
  45: "Toledo",
  46: "Valencia",
  47: "Valladolid",
  48: "Vizcaya",
  49: "Zamora",
  50: "Zaragoza",
};

